"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "az";

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// Define translation dictionary
export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.gov": "Governance & Policy",
    "nav.env": "Environmental Strategy",
    "nav.soc": "Social Impact",
    "nav.res": "SDG Research",
    "nav.edu": "Education & Curriculum",
    "nav.gov2": "Governance & Accountability",
    "nav.strat": "Strategy & Reporting",
    "nav.res2": "Research",
    "nav.edu2": "Education",
    "nav.comm": "Community & Social Impact",
    "nav.nav": "Navigation",
    "nav.sfa": "Strategic Focus Areas",
    "sdu.sus": "Sustainability",

    // Hero
    "hero.badge": "Sumgayit State University",
    "hero.title": "SDU: Shaping a <br class='hidden md:block' /> Sustainable Future, Today",
    "hero.desc": "Discover how we are transforming our campus and community for a better future through data-driven sustainable solutions aligned with the UN's SDGs.",
    "hero.explore": "Explore Our Impact",
    "hero.join": "Join Our Initiatives",

    // Strategic Focus Areas
    "sfa.badge": "Strategic Framework",
    "sfa.title": "Strategic Focus Areas",
    "sfa.desc": "Our sustainability agenda is structured around five interconnected pillars, each designed to create lasting, systemic change across campus and the wider community.",
    "sfa.focus1.title": "Governance & Policy",
    "sfa.focus1.desc": "Building transparent institutional frameworks, ethical decision-making processes, and evidence-based sustainability policies that drive long-term impact.",
    "sfa.focus2.title": "Environmental Strategy & Reporting",
    "sfa.focus2.desc": "Measuring, managing, and publishing our carbon footprint, energy consumption, and biodiversity impact through rigorous annual GRI-aligned reports.",
    "sfa.focus3.title": "Social Impact & Inclusion",
    "sfa.focus3.desc": "Advancing equity and belonging through inclusive access programs, disability support, gender equality initiatives, and community outreach partnerships.",
    "sfa.focus4.title": "SDG Research Outputs",
    "sfa.focus4.desc": "Producing peer-reviewed research, policy briefs, and innovation projects that directly contribute measurable progress to the UN's 17 Global Goals.",
    "sfa.focus5.title": "Education & Curriculum Integration",
    "sfa.focus5.desc": "Embedding sustainability competencies across all degree programmes, equipping every SDU graduate with the knowledge to lead the green transition.",
    "sfa.learn_more": "Learn more",
    "sfa.more_soon": "More initiatives coming soon",

    // SDG Grid
    "sdg.title": "SDG Goals in Action",
    "sdg.desc": "Our 12 active UN Sustainable Development Goals and the concrete contributions SDU is making toward each one.",
    "sdg.show_less": "Show Less",
    "sdg.see_all": "See All 12 Active Goals",
    
    // Impact Dashboard
    "impact.badge": "Live Data",
    "impact.title": "Impact Dashboard",
    "impact.desc": "Real-time metrics tracking our progress toward carbon neutrality and zero-waste campus operations.",
    "impact.carbon.title": "Carbon Offset",
    "impact.carbon.metric": "1,245",
    "impact.carbon.unit": "tons",
    "impact.energy.title": "Renewable Energy",
    "impact.energy.metric": "320",
    "impact.energy.unit": "MWh",
    "impact.waste.title": "Waste Recycled",
    "impact.waste.metric": "4,150",
    "impact.waste.unit": "kg",
    "impact.water.title": "Water Saved",
    "impact.water.metric": "1.2",
    "impact.water.unit": "M liters",
    "impact.chart.title": "Energy Consumption & Savings",
    "impact.chart.desc": "Monthly tracking (2024)",
    
    // Bento Activities
    "bento.title": "University Initiatives",
    "bento.desc": "Discover how we integrate sustainability into every aspect of campus life, from policy to research and student engagement.",
    "bento.card1.title": "Education & Curriculum",
    "bento.card1.desc": "More than 40 degree programs now reflect integrated coursework aimed at the UN Sustainable Development Goals.",
    "bento.card1.link": "View Courses",
    "bento.card2.title": "Social Impact and Inclusion",
    "bento.card2.desc": "Student Environmental Initiatives driving community awareness.",
    "bento.card3.title": "Governance & Policy",
    "bento.card3.desc": "Access our official Sustainability Strategy 2024-2030 document.",
    "bento.card3.link": "Download PDF",
    "bento.card4.badge": "Latest Research",
    "bento.card4.title": "\"Innovations in Renewable Energy Storage in Urban Environments\"",
    
    // Carbon Calculator
    "calc.badge": "Interactive Tool",
    "calc.title": "Carbon Footprint Calculator",
    "calc.desc": "Measure the impact of your daily habits on nature and find out how many trees you need to offset it.",
    "calc.monthly": "Monthly Indicators",
    "calc.elec.title": "Electricity Consumption",
    "calc.elec.unit": "Monthly, kWh",
    "calc.trans.title": "Transport Footprint",
    "calc.trans.unit": "Monthly, km",
    "calc.gas.title": "Natural Gas",
    "calc.gas.unit": "Monthly, m³",
    "calc.total.badge": "Total Emission",
    "calc.total.desc": "This represents your estimated monthly carbon footprint (CO₂).",
    "calc.tree.title": "Trees needed to offset",
    "calc.tree.unit": "trees/year",
    
    // Events
    "events.title": "Upcoming Events",
    "events.desc": "Stay engaged with SDU's greening and sustainable development activities. Every step makes a difference.",
    "events.view_all": "View All Events",
    "events.event1.title": "Green Campus Day: Mass Tree Planting",
    "events.event1.month": "Oct",
    "events.event1.loc": "In front of Registration Center",
    "events.event1.cat": "Action",
    "events.event2.title": "Recycling Seminar: The Future is in Our Hands",
    "events.event2.month": "Oct",
    "events.event2.loc": "Assembly Hall",
    "events.event2.cat": "Education",
    "events.event3.title": "Alternative Energy Sources Exhibition",
    "events.event3.month": "Nov",
    "events.event3.loc": "Main Building Foyer",
    "events.event3.cat": "Exhibition",
    "events.register": "Register",
    
    // Gallery
    "gallery.title": "Environment and Community",
    "gallery.desc": "The brightest moments of our sustainability initiatives on campus.",

    // FAQ
    "faq.title": "Frequently Asked Questions",
    "faq.desc": "Answers to your questions about SDU's sustainable development activities.",
    "faq.q1": "What are SDGs (Sustainable Development Goals)?",
    "faq.a1": "The Sustainable Development Goals are 17 global goals proposed by the UN aimed at eradicating poverty, protecting the planet, and ensuring peace and prosperity for all. As SDU, we strongly support these goals with our policies and research.",
    "faq.q2": "How can students join ecological projects?",
    "faq.a2": "Our students can join the 'Green Campus' tree planting actions, recycling workshops, and Sustainability Incubator held throughout the year by registering directly from the Events Calendar section on our portal.",
    "faq.q3": "What is the university's 2030 goal?",
    "faq.a3": "Our main goal is to achieve full zero carbon emissions (Net-Zero) within the campus by 2030, switch to renewable energy, and become one of the leading higher education institutions in global sustainability rankings.",
    "faq.q4": "Where are recycling bins located on campus?",
    "faq.a4": "Specially marked smart recycling bins (paper, plastic, and general waste) are available in the foyers of main educational buildings, the library, the dining area, and at the entrances of dormitories.",

    // Contact
    "contact.title": "Contact and Location",
    "contact.desc": "Contact us or visit the campus for a more sustainable future.",
    "contact.info_center": "Information Center",
    "contact.address.label": "Address",
    "contact.address": "Sumgait city, 43rd block, Sumgait State University Main Building (SDG Center)",
    "contact.phone.label": "Phone",
    "contact.email.label": "Email",
    "contact.hours.label": "Working Hours",
    "contact.hours": "Mon - Fri : 09:00 - 18:00",
    "contact.link": "Visit Official Website",

    // Footer
    "footer.rights": "All rights reserved.",

    // Environmental Strategy Page
    "env.badge": "Strategic Focus Area 2",
    "env.title": "Environmental Strategy",
    "env.desc": "Measuring, managing, and publishing our carbon footprint, energy consumption, and biodiversity impact through rigorous GRI-aligned annual reports.",

    "env.metric1.label": "Carbon reduction vs 2020 baseline",
    "env.metric2.label": "Renewable energy generated",
    "env.metric3.label": "Water saved annually",
    "env.metric4.label": "Target by 2030",

    "env.initiatives.title": "Active Initiatives",

    "env.init1.title": "Solar Energy Expansion",
    "env.init1.status": "Active",
    "env.init1.desc": "Installing 500kW solar panels across campus rooftops to cover 40% of energy needs by 2025.",

    "env.init2.title": "Rainwater Harvesting System",
    "env.init2.status": "Active",
    "env.init2.desc": "Campus-wide collection infrastructure now recovers over 1.2 million litres of water annually.",

    "env.init3.title": "Zero-Waste Campus Programme",
    "env.init3.status": "In Progress",
    "env.init3.desc": "Waste segregation stations, composting, and single-use plastic elimination across all buildings.",

    "env.init4.title": "Urban Green Belt",
    "env.init4.status": "Planned",
    "env.init4.desc": "3-hectare biodiversity corridor with native plant species bordering the main campus.",

    "env.cta.title": "Access our Environmental Reports",
    "env.cta.desc": "Full GRI-aligned sustainability reports are available for download from the SDU Document Portal.",
    "env.cta.btn": "Back to Home",

    // Social Impact Page
    "soc.badge": "Strategic Focus Area 3",
    "soc.title": "Social Impact & Inclusion",
    "soc.desc": "Advancing equity and belonging through inclusive access programs, disability support, gender equality initiatives, and community outreach partnerships.",
    "soc.metric1.label": "Students receiving financial aid",
    "soc.metric2.label": "Women in STEM programs",
    "soc.metric3.label": "Community outreach projects",
    "soc.metric4.label": "Campus accessibility rating",
    "soc.initiatives.title": "Active Initiatives",
    "soc.init1.title": "Women in STEM Mentorship",
    "soc.init1.desc": "Connecting female students with industry leaders to boost representation in technical fields.",
    "soc.init1.status": "Active",
    "soc.init2.title": "Accessible Campus Initiative",
    "soc.init2.desc": "Upgrading all campus facilities with ramps, elevators, and braille signage.",
    "soc.init2.status": "In Progress",
    "soc.init3.title": "Rural Student Support Fund",
    "soc.init3.desc": "Providing housing and stipends for students from remote regions.",
    "soc.init3.status": "Active",
    "soc.init4.title": "Community Volunteering Program",
    "soc.init4.desc": "Coordinating student volunteer hours for local NGOs and schools.",
    "soc.init4.status": "Planned",
    "soc.cta.title": "Join Our Community Efforts",
    "soc.cta.desc": "Get involved in our social initiatives and make a difference today.",
    "soc.cta.btn": "Explore Opportunities",

    // SDG Research Page
    "res.badge": "Strategic Focus Area 4",
    "res.title": "SDG Research Outputs",
    "res.desc": "Producing peer-reviewed research, policy briefs, and innovation projects that directly contribute measurable progress to the UN's 17 Global Goals.",
    "res.metric1.label": "Peer-reviewed papers published",
    "res.metric2.label": "Active SDG research grants",
    "res.metric3.label": "International partnerships",
    "res.metric4.label": "Student research projects",
    "res.initiatives.title": "Key Research Projects",
    "res.init1.title": "Renewable Energy Lab",
    "res.init1.desc": "Developing cost-effective solar storage solutions for urban environments.",
    "res.init1.status": "Active",
    "res.init2.title": "Caspian Sea Biodiversity Study",
    "res.init2.desc": "Tracking marine life changes and pollution levels in partnership with global NGOs.",
    "res.init2.status": "In Progress",
    "res.init3.title": "Sustainable Agriculture Tech",
    "res.init3.desc": "Testing IoT sensors for water optimization in regional farming.",
    "res.init3.status": "Planned",
    "res.init4.title": "Green Economy Policy Briefs",
    "res.init4.desc": "Advising local government on circular economy transitions.",
    "res.init4.status": "Active",
    "res.cta.title": "Access our Research Portal",
    "res.cta.desc": "Read our latest publications and discover collaboration opportunities.",
    "res.cta.btn": "View Publications",

    // Education & Curriculum Page
    "edu.badge": "Strategic Focus Area 5",
    "edu.title": "Education & Curriculum",
    "edu.desc": "Embedding sustainability competencies across all degree programmes, equipping every SDU graduate with the knowledge to lead the green transition.",
    "edu.metric1.label": "Courses integrating SDGs",
    "edu.metric2.label": "Dedicated sustainability degrees",
    "edu.metric3.label": "Faculty trained in green education",
    "edu.metric4.label": "Students enrolled in green courses",
    "edu.initiatives.title": "Curriculum Updates",
    "edu.init1.title": "Mandatory 'Green Transition' Core Course",
    "edu.init1.desc": "A foundational course required for all first-year students across all faculties.",
    "edu.init1.status": "Active",
    "edu.init2.title": "MSc in Sustainable Development",
    "edu.init2.desc": "New interdisciplinary master's degree launching next academic year.",
    "edu.init2.status": "In Progress",
    "edu.init3.title": "Faculty Green Training Workshops",
    "edu.init3.desc": "Equipping professors with tools to integrate SDGs into existing syllabi.",
    "edu.init3.status": "Active",
    "edu.init4.title": "Student Sustainability Incubator",
    "edu.init4.desc": "A lab for students to develop and prototype eco-friendly business models.",
    "edu.init4.status": "Planned",
    "edu.cta.title": "Review Our Academic Offerings",
    "edu.cta.desc": "Explore syllabi, green degrees, and training programs at SDU.",
    "edu.cta.btn": "View Course Catalog",

    // Governance & Policy Page
    "gov.title": "Governance & Policy",
    "gov.desc": "Building transparent institutional frameworks, ethical decision-making processes, and evidence-based sustainability policies that drive long-term impact.",
    "gov.pillars.title": "Our Governance Pillars",
    "gov.pillars.desc": "Four interconnected principles that underpin how SDU governs its sustainability agenda.",
    "gov.pillar1.title": "Institutional Integrity",
    "gov.pillar1.desc": "Establishing robust governance frameworks that embed sustainability accountability at every level of university leadership.",
    "gov.pillar2.title": "Evidence-Based Policy",
    "gov.pillar2.desc": "Drafting and reviewing sustainability policies grounded in peer-reviewed data, international benchmarks, and stakeholder consultation.",
    "gov.pillar3.title": "Transparent Reporting",
    "gov.pillar3.desc": "Publishing annual sustainability reports compliant with GRI and IESBA standards, ensuring complete public accountability.",
    "gov.pillar4.title": "Stakeholder Engagement",
    "gov.pillar4.desc": "Creating meaningful dialogue between faculty, students, government authorities, and NGOs to co-design sustainability initiatives.",
    "gov.docs.title": "Policy Documents",
    "gov.doc1.title": "SDU Sustainability Strategy 2024–2030",
    "gov.doc1.tag": "Strategy",
    "gov.doc2.title": "Annual GRI Sustainability Report",
    "gov.doc2.tag": "Report",
    "gov.doc3.title": "Campus Carbon Neutrality Roadmap",
    "gov.doc3.tag": "Roadmap",
    "gov.doc4.title": "Stakeholder Engagement Charter",
    "gov.doc4.tag": "Policy",
    "gov.cta.title": "Contribute to Our Policy Work",
    "gov.cta.desc": "Faculty, students, and community partners can submit policy proposals through the SDU Sustainability Portal.",
    "gov.cta.btn": "Back to Home",

    // Governance & Accountability (Page 2)
    "gov2.intro": "Sumgayit State University is committed to responsible governance and transparent institutional practices that support sustainable development. The University has established a set of policies and governance mechanisms that guide ethical conduct, equality and inclusion, environmental responsibility, and responsible financial management.",
    "gov2.section1.title": "Institutional Governance & Sustainability Framework",
    "gov2.section1.desc": "Our governance structure ensures accountability at every level, with clear lines of responsibility for sustainability outcomes.",
    "gov2.section2.title": "Key Policies",
    "gov2.policy1.title": "Academic Freedom Policy",
    "gov2.policy1.desc": "Policy ensuring the protection of academic freedom, open inquiry, and intellectual diversity within the university.",
    "gov2.policy2.title": "Anticorruption Policy",
    "gov2.policy2.desc": "Framework for preventing corruption, promoting transparency, and ensuring ethical conduct across all university operations.",
    "gov2.policy3.title": "Antidiscrimination Policy",
    "gov2.policy3.desc": "Policy prohibiting all forms of discrimination and fostering an inclusive, respectful academic environment.",
    "gov2.policy4.title": "Anti-Harassment Policy",
    "gov2.policy4.desc": "Comprehensive guidelines to prevent harassment and ensure a safe learning and working environment for all members.",
    "gov2.policy5.title": "Climate Action and Sustainability Policy",
    "gov2.policy5.desc": "Strategic policy addressing climate change through carbon reduction, green initiatives, and sustainable campus operations.",
    "gov2.policy6.title": "Equality, Diversity & Inclusion Policy",
    "gov2.policy6.desc": "Policy promoting equal opportunities, celebrating diversity, and building an inclusive university culture.",
    "gov2.policy7.title": "Equality, Diversity & Inclusion Framework",
    "gov2.policy7.desc": "Structured framework outlining strategies and action plans for advancing equality, diversity, and inclusion.",
    "gov2.policy8.title": "Inclusive Education and Accessibility Framework",
    "gov2.policy8.desc": "Framework ensuring accessible education for all students, including those with disabilities and special needs.",
    "gov2.policy9.title": "Policy on Ethical Organizational Values",
    "gov2.policy9.desc": "Guidelines establishing ethical standards and core values for organizational governance and decision-making.",
    "gov2.policy10.title": "Policy on Ethical Values",
    "gov2.policy10.desc": "Policy defining ethical principles guiding student and staff conduct in academic and professional settings.",
    "gov2.policy11.title": "Prevention Policy on Human Trafficking",
    "gov2.policy11.desc": "Policy outlining measures to prevent human trafficking and protect vulnerable individuals within the university community.",
    "gov2.policy12.title": "Student Safety Policy",
    "gov2.policy12.desc": "Comprehensive policy ensuring the physical and psychological safety of students across all campus activities.",
    "gov2.policy13.title": "Sustainability Policy on Donations and Funding",
    "gov2.policy13.desc": "Guidelines ensuring that donations and funding sources align with the university's sustainability and ethical standards.",
    "gov2.policy14.title": "Sustainable Investment Policy",
    "gov2.policy14.desc": "Policy guiding investment decisions toward environmentally and socially responsible opportunities.",
    "gov2.policy15.title": "Sustainable Procurement Policy",
    "gov2.policy15.desc": "Framework for sourcing goods and services that meet environmental, social, and economic sustainability criteria.",
    "gov2.section3.title": "Sustainability Leadership & Committees",
    "gov2.section3.desc": "Dedicated teams driving our sustainability agenda forward.",
    "gov2.committee1.title": "Sustainability Steering Committee",
    "gov2.committee1.desc": "Executive leadership overseeing strategic sustainability initiatives.",
    "gov2.committee2.title": "Working Groups",
    "gov2.committee2.desc": "Cross-functional teams implementing specific sustainability projects.",
    "gov2.committee3.title": "Leadership Team",
    "gov2.committee3.desc": "Senior management accountable for sustainability outcomes.",
    "gov2.section4.title": "Institutional Commitments",
    "gov2.commitment1.title": "UN SDG Commitment",
    "gov2.commitment1.desc": "Aligned with all 17 Sustainable Development Goals.",
    "gov2.commitment2.title": "Carbon Neutrality Goal",
    "gov2.commitment2.desc": "Targeting net-zero emissions by 2030.",
    "gov2.commitment3.title": "Transparency Pledge",
    "gov2.commitment3.desc": "Annual public reporting on sustainability performance.",
    "gov2.commitment4.title": "Community Partnership",
    "gov2.commitment4.desc": "Collaborative approach with local stakeholders.",
    "gov2.cta": "Learn More About Our Governance",

    // Strategy & Reporting
    "strat.intro": "Sumgayit State University is gradually integrating sustainability principles into its institutional strategy and planning processes. The University aligns its activities with the United Nations Sustainable Development Goals (SDGs) and works to monitor progress through internal reporting and evaluation mechanisms.",
    "strat.section1.title": "Climate Action and Sustainability Strategy",
    "strat.strategy1.title": "Carbon Reduction Strategy",
    "strat.strategy1.desc": "Comprehensive plan to reduce carbon emissions by 50% by 2027.",
    "strat.strategy2.title": "Energy Transition Plan",
    "strat.strategy2.desc": "Shifting to 100% renewable energy sources by 2028.",
    "strat.strategy3.title": "Biodiversity Protection",
    "strat.strategy3.desc": "Preserving and enhancing campus ecosystems and native species.",
    "strat.section2.title": "SDG Alignment",
    "strat.sdg.desc": "Our activities align with all 17 UN Sustainable Development Goals.",
    "strat.section3.title": "Sustainability Goals & Priorities",
    "strat.goal1.title": "Net-Zero by 2030",
    "strat.goal1.desc": "Achieve carbon neutrality across all campus operations.",
    "strat.goal2.title": "Zero Waste Campus",
    "strat.goal2.desc": "Divert 90% of waste from landfills through reduction and recycling.",
    "strat.goal3.title": "100% Renewable Energy",
    "strat.goal3.desc": "Power all facilities with clean, renewable sources.",
    "strat.goal4.title": "Water Conservation",
    "strat.goal4.desc": "Reduce water consumption by 40% through efficiency measures.",
    "strat.goal5.title": "Green Education for All",
    "strat.goal5.desc": "Integrate sustainability into every degree program.",
    "strat.section4.title": "SDG Reports & Progress",
    "strat.report1.title": "Annual Sustainability Report 2024",
    "strat.report2.title": "SDG Progress Report 2023",
    "strat.report3.title": "Climate Action Update 2024",
    "strat.report4.title": "GRI Compliance Report",
    "strat.download": "Download PDF",
    "strat.section5.title": "Key Indicators",
    "strat.indicator1": "Carbon Emissions",
    "strat.indicator2": "Renewable Energy",
    "strat.indicator3": "Waste Recycled",
    "strat.indicator4": "Water Saved",
    "strat.indicator5": "Green Courses",
    "strat.indicator6": "Community Projects",
    "strat.cta": "Download Full Reports",

    // Research for Sustainable Development (Page 2)
    "res2.intro": "The historical industrial development of Sumgayit provides a unique context for sustainability research. Today, the city's ongoing environmental improvements and restoration efforts offer opportunities for research on ecological recovery, pollution mitigation, and sustainable resource management.",
    "res2.section1.title": "Sumqayıt: Research Context",
    "res2.section2.title": "SDG-related Research Projects",
    "res2.project1.title": "Renewable Energy Storage",
    "res2.project1.desc": "Developing cost-effective solar storage solutions for urban environments.",
    "res2.project2.title": "Caspian Sea Biodiversity",
    "res2.project2.desc": "Tracking marine life changes and pollution levels in partnership with global NGOs.",
    "res2.project3.title": "Sustainable Agriculture",
    "res2.project3.desc": "Testing IoT sensors for water optimization in regional farming.",
    "res2.project4.title": "Air Quality Monitoring",
    "res2.project4.desc": "Real-time air quality tracking across industrial and residential zones.",
    "res2.project5.title": "Green Economy Policy",
    "res2.project5.desc": "Advising local government on circular economy transitions.",
    "res2.project6.title": "Waste Management Tech",
    "res2.project6.desc": "Innovative solutions for waste reduction and recycling.",
    "res2.section3.title": "Research Partnerships",
    "res2.partner1.title": "International Universities",
    "res2.partner2.title": "Research Institutes",
    "res2.partner3.title": "NGOs & Foundations",
    "res2.partner4.title": "Government Agencies",
    "res2.partner5.title": "Industry Partners",
    "res2.section4.title": "Research Centres & Laboratories",
    "res2.center1.title": "Renewable Energy Lab",
    "res2.center1.desc": "Advanced research in solar, wind, and energy storage technologies.",
    "res2.center2.title": "Environmental Research Center",
    "res2.center2.desc": "Monitoring and analyzing local ecosystem health and biodiversity.",
    "res2.center3.title": "Sustainability Innovation Hub",
    "res2.center3.desc": "Incubating green technologies and sustainable business models.",
    "res2.center4.title": "Data Analytics Lab",
    "res2.center4.desc": "Big data solutions for sustainability metrics and reporting.",
    "res2.section5.title": "Student Research Projects",
    "res2.student1.title": "Undergraduate Projects",
    "res2.student2.title": "Master's Theses",
    "res2.student3.title": "PhD Dissertations",
    "res2.student4.title": "Innovation Challenge Winners",
    "res2.student5.title": "Grant Recipients",
    "res2.cta": "Explore Research Opportunities",

    // Sustainable Education (Page 2)
    "edu2.intro": "Sumgayit State University promotes education that encourages awareness of sustainability and responsible citizenship. Sustainability-related topics are gradually being integrated into teaching, student activities, and academic initiatives.",
    "edu2.section1.title": "Sustainability Topics in Curriculum",
    "edu2.topic1.title": "Climate Change Science",
    "edu2.topic1.desc": "Understanding the scientific basis of climate change and its impacts.",
    "edu2.topic2.title": "Circular Economy",
    "edu2.topic2.desc": "Principles of waste reduction and resource efficiency.",
    "edu2.topic3.title": "Social Responsibility",
    "edu2.topic3.desc": "Ethical business practices and community engagement.",
    "edu2.topic4.title": "Environmental Ethics",
    "edu2.topic4.desc": "Philosophical foundations of environmental stewardship.",
    "edu2.topic5.title": "Green Technology",
    "edu2.topic5.desc": "Innovations in clean energy and sustainable materials.",
    "edu2.topic6.title": "Sustainable Development Goals",
    "edu2.topic6.desc": "Global framework for addressing sustainability challenges.",
    "edu2.section2.title": "Relevant Courses & Programs",
    "edu2.course1.title": "Introduction to Sustainability",
    "edu2.course1.desc": "Foundational concepts and principles of sustainable development.",
    "edu2.course2.title": "Environmental Management",
    "edu2.course2.desc": "Systems approach to managing environmental resources.",
    "edu2.course3.title": "Green Business Practices",
    "edu2.course3.desc": "Sustainable strategies for modern organizations.",
    "edu2.course4.title": "Renewable Energy Systems",
    "edu2.course4.desc": "Design and implementation of clean energy solutions.",
    "edu2.course5.title": "Sustainable Urban Planning",
    "edu2.course5.desc": "Creating livable, efficient, and green cities.",
    "edu2.course6.title": "MSc in Sustainable Development",
    "edu2.course6.desc": "Advanced interdisciplinary master's program.",
    "edu2.section3.title": "Student Sustainability Initiatives",
    "edu2.init1.title": "Academic Freedom Policy",
    "edu2.init1.desc": "Policy ensuring the protection of academic freedom, open inquiry, and intellectual diversity within the university.",
    "edu2.init2.title": "Anticorruption Policy",
    "edu2.init2.desc": "Framework for preventing corruption, promoting transparency, and ensuring ethical conduct across all university operations.",
    "edu2.init3.title": "Antidiscrimination Policy",
    "edu2.init3.desc": "Policy prohibiting all forms of discrimination and fostering an inclusive, respectful academic environment.",
    "edu2.init4.title": "Anti-Harassment Policy",
    "edu2.init4.desc": "Comprehensive guidelines to prevent harassment and ensure a safe learning and working environment for all members.",
    "edu2.init5.title": "Climate Action and Sustainability Policy",
    "edu2.init5.desc": "Strategic policy addressing climate change through carbon reduction, green initiatives, and sustainable campus operations.",
    "edu2.init6.title": "Equality, Diversity & Inclusion Policy",
    "edu2.init6.desc": "Policy promoting equal opportunities, celebrating diversity, and building an inclusive university culture.",
    "edu2.init7.title": "Equality, Diversity & Inclusion Framework",
    "edu2.init7.desc": "Structured framework outlining strategies and action plans for advancing equality, diversity, and inclusion.",
    "edu2.init8.title": "Inclusive Education and Accessibility Framework",
    "edu2.init8.desc": "Framework ensuring accessible education for all students, including those with disabilities and special needs.",
    "edu2.init9.title": "Policy on Ethical Organizational Values",
    "edu2.init9.desc": "Guidelines establishing ethical standards and core values for organizational governance and decision-making.",
    "edu2.init10.title": "Policy on Ethical Values",
    "edu2.init10.desc": "Policy defining ethical principles guiding student and staff conduct in academic and professional settings.",
    "edu2.init11.title": "Prevention Policy on Human Trafficking",
    "edu2.init11.desc": "Policy outlining measures to prevent human trafficking and protect vulnerable individuals within the university community.",
    "edu2.init12.title": "Student Safety Policy",
    "edu2.init12.desc": "Comprehensive policy ensuring the physical and psychological safety of students across all campus activities.",
    "edu2.init13.title": "Sustainability Policy on Donations and Funding",
    "edu2.init13.desc": "Guidelines ensuring that donations and funding sources align with the university's sustainability and ethical standards.",
    "edu2.init14.title": "Sustainable Investment Policy",
    "edu2.init14.desc": "Policy guiding investment decisions toward environmentally and socially responsible opportunities.",
    "edu2.init15.title": "Sustainable Procurement Policy",
    "edu2.init15.desc": "Framework for sourcing goods and services that meet environmental, social, and economic sustainability criteria.",
    "edu2.section4.title": "Eco-Club Activities",
    "edu2.eco1.title": "Tree Planting Events",
    "edu2.eco2.title": "Beach Cleanups",
    "edu2.eco3.title": "Sustainability Workshops",
    "edu2.eco4.title": "Documentary Screenings",
    "edu2.section5.title": "Workshops & Seminars",
    "edu2.workshop1.title": "Guest Lectures",
    "edu2.workshop2.title": "Expert Panels",
    "edu2.workshop3.title": "Hands-on Training",
    "edu2.workshop4.title": "Career Fairs",
    "edu2.workshop5.title": "Research Symposia",
    "edu2.cta": "View Course Catalog",

    // Community & Social Impact
    "comm.intro": "The University recognizes the importance of contributing to the development of society and the local community. Through partnerships, outreach activities, and public engagement initiatives, Sumgayit State University works to promote social inclusion, environmental awareness, and community development.",
    "comm.section1.title": "Community Outreach Projects",
    "comm.outreach1.title": "Rural Education Support",
    "comm.outreach1.desc": "Providing educational resources to underserved rural areas.",
    "comm.outreach2.title": "Healthcare Awareness",
    "comm.outreach2.desc": "Public health education and screening programs.",
    "comm.outreach3.title": "Digital Literacy Program",
    "comm.outreach3.desc": "Teaching digital skills to community members of all ages.",
    "comm.outreach4.title": "Youth Empowerment",
    "comm.outreach4.desc": "Leadership development and mentorship for young people.",
    "comm.outreach5.title": "Elderly Care Initiative",
    "comm.outreach5.desc": "Support services and companionship for senior citizens.",
    "comm.outreach6.title": "Disability Support",
    "comm.outreach6.desc": "Accessibility improvements and assistance programs.",
    "comm.section2.title": "Partnerships",
    "comm.partner1.title": "Local Government",
    "comm.partner2.title": "International NGOs",
    "comm.partner3.title": "Community Organizations",
    "comm.partner4.title": "Private Sector",
    "comm.partner5.title": "Media Partners",
    "comm.partner6.title": "Academic Institutions",
    "comm.section3.title": "Volunteering Initiatives",
    "comm.volunteer1.title": "Student Volunteer Corps",
    "comm.volunteer1.desc": "Organized student volunteering across various causes.",
    "comm.volunteer2.title": "Faculty Pro Bono Program",
    "comm.volunteer2.desc": "Professional services donated by faculty members.",
    "comm.volunteer3.title": "Alumni Mentorship",
    "comm.volunteer3.desc": "Graduates mentoring current students and community youth.",
    "comm.volunteer4.title": "Community Service Days",
    "comm.volunteer4.desc": "Coordinated days of service across the university.",
    "comm.volunteer5.title": "Emergency Response Team",
    "comm.volunteer5.desc": "Rapid response volunteers for community emergencies.",
    "comm.section4.title": "Sustainability Awareness Campaigns",
    "comm.campaign1.title": "Climate Action Week",
    "comm.campaign2.title": "Zero Waste Challenge",
    "comm.campaign3.title": "Biodiversity Month",
    "comm.campaign4.title": "Green Transportation Day",
    "comm.section5.title": "Student Engagement Activities",
    "comm.activity1.title": "Sustainability Hackathon",
    "comm.activity2.title": "Community Garden Project",
    "comm.activity3.title": "Social Innovation Lab",
    "comm.activity4.title": "Cultural Exchange Events",
    "comm.activity5.title": "Leadership Training",
    "comm.cta": "Join Our Community",
  },
  az: {
    // Navbar
    "nav.gov": "İdarəetmə və Siyasət",
    "nav.env": "Ekoloji Strategiya",
    "nav.soc": "Sosial Təsir",
    "nav.res": "DİM Tədqiqatları",
    "nav.edu": "Təhsil və Kurikulum",
    "nav.gov2": "İdarəetmə və Hesabatlılıq",
    "nav.strat": "Strategiya və Hesabatlılıq",
    "nav.res2": "Tədqiqat",
    "nav.edu2": "Təhsil",
    "nav.comm": "İcma və Sosial Təsir",
    "nav.nav": "Naviqasiya",
    "nav.sfa": "Strateji İstiqamətlər",
    "sdu.sus": "Dayanıqlılıq",

    // Hero
    "hero.badge": "Sumqayıt Dövlət Universiteti",
    "hero.title": "SDU: Dayanıqlı Gələcəyi <br class='hidden md:block' /> Bu Gündən Şəkilləndiririk",
    "hero.desc": "BMT-nin DİM-lərinə uyğun olaraq məlumatlara əsaslanan dayanıqlı həllər vasitəsilə kampüsümüzü və cəmiyyətimizi necə dəyişdiyimizi kəşf edin.",
    "hero.explore": "Təsirimizlə Tanış Olun",
    "hero.join": "Təşəbbüslərimizə Qoşulun",

    // Strategic Focus Areas
    "sfa.badge": "Strateji Çərçivə",
    "sfa.title": "Strateji İstiqamətlər",
    "sfa.desc": "Davamlılıq gündəmimiz kampüs və daha geniş icmada qalıcı, sistemli dəyişiklik yaratmaq üçün nəzərdə tutulmuş beş bir-biri ilə əlaqəli sütun ətrafında qurulub.",
    "sfa.focus1.title": "İdarəetmə və Siyasət",
    "sfa.focus1.desc": "Uzunmüddətli təsir göstərən şəffaf institusional çərçivələrin, etik qərar qəbuletmə proseslərinin və sübutlara əsaslanan siyasətlərin qurulması.",
    "sfa.focus2.title": "Ekoloji Strategiya və Hesabatlılıq",
    "sfa.focus2.desc": "Karbon izi, enerji sərfiyyatı və biomüxtəlifliyə təsiri GRI standartlarına cavab verən illik hesabatlar vasitəsilə ölçmək və idarə etmək.",
    "sfa.focus3.title": "Sosial Təsir və İnklüzivlik",
    "sfa.focus3.desc": "İnklüziv proqramlar, əlilliyi olan şəxslərə dəstək, gender bərabərliyi təşəbbüsləri vasitəsilə ədaləti inkişaf etdirmək.",
    "sfa.focus4.title": "DİM Tədqiqat Nəticələri",
    "sfa.focus4.desc": "BMT-nin 17 Qlobal Məqsədinə birbaşa töhfə verən tədqiqat, siyasət xülasələri və innovasiya layihələrinin istehsalı.",
    "sfa.focus5.title": "Təhsil və Kurikulum İnteqrasiyası",
    "sfa.focus5.desc": "Bütün dərəcə proqramlarına davamlılıq kompetensiyalarının daxil edilməsi.",
    "sfa.learn_more": "Daha ətraflı",
    "sfa.more_soon": "Daha çox təşəbbüs tezliklə",

    // SDG Grid
    "sdg.title": "DİM Hədəfləri Fəaliyyətdə",
    "sdg.desc": "SDU-nun 12 aktiv BMT Davamlı İnkişaf Məqsədi və hər birinə verdiyi konkret töhfələr.",
    "sdg.show_less": "Daha Az Göstər",
    "sdg.see_all": "Bütün 12 Aktiv Hədəfi Göstər",
    
    // Impact Dashboard
    "impact.badge": "Canlı Məlumatlar",
    "impact.title": "Təsir Paneli",
    "impact.desc": "Karbon neytrallığı və tullantısız kampüs əməliyyatlarına doğru irəliləyişimizi izləyən real vaxt göstəriciləri.",
    "impact.carbon.title": "Azaldılmış Karbon",
    "impact.carbon.metric": "1,245",
    "impact.carbon.unit": "ton",
    "impact.energy.title": "Bərpa Olunan Enerji",
    "impact.energy.metric": "320",
    "impact.energy.unit": "MWh",
    "impact.waste.title": "Təkrar Emal Edilən Tullantı",
    "impact.waste.metric": "4,150",
    "impact.waste.unit": "kq",
    "impact.water.title": "Su Qənaəti",
    "impact.water.metric": "1.2",
    "impact.water.unit": "M litr",
    "impact.chart.title": "Enerji İstehlakı & Qənaət",
    "impact.chart.desc": "Aylıq izləmə (2024)",
    
    // Bento Activities
    "bento.title": "Universitet Təşəbbüsləri",
    "bento.desc": "SDU kampüsündə həyata keçirilən davamlı inkişaf layihələri və aktiv tədbirlərimizlə tanış olun.",
    "bento.card1.title": "Təhsil və Kurikulum",
    "bento.card1.desc": "Artıq 40-dan çox dərəcə proqramımız BMT-nin Dayanıqlı İnkişaf Məqsədlərinə yönəlmiş inteqrasiya olunmuş kursları özündə əks etdirir.",
    "bento.card1.link": "Kurslara Bax",
    "bento.card2.title": "Sosial Təsir və İnklüzivlik",
    "bento.card2.desc": "İcma fərqindəliyini artıran Tələbə Ekoloji Təşəbbüsləri.",
    "bento.card3.title": "İdarəetmə və Siyasət",
    "bento.card3.desc": "Rəsmi Davamlılıq Strategiyası 2024-2030 sənədimizlə tanış olun.",
    "bento.card3.link": "Sənədi Yüklə",
    "bento.card4.badge": "Ən Son Tədqiqat",
    "bento.card4.title": "\"Şəhər Mühitlərində Bərpa Olunan Enerji Saxlanmasında İnnovasiyalar\"",
    
    // Carbon Calculator
    "calc.badge": "İnteraktiv Alət",
    "calc.title": "Karbon İzi Kalkulyatoru",
    "calc.desc": "Kampüs daxilində gündəlik fəaliyyətlərinizin təbiətə təsirini hesablayın və kompensasiya yollarını öyrənin.",
    "calc.monthly": "Aylıq Göstəricilər",
    "calc.elec.title": "Elektrik Sərfiyyatı",
    "calc.elec.unit": "Aylıq, kWh",
    "calc.trans.title": "Nəqliyyat İzləri",
    "calc.trans.unit": "Aylıq, km",
    "calc.gas.title": "Təbii Qaz",
    "calc.gas.unit": "Aylıq, m³",
    "calc.total.badge": "Ümumi Emissiya",
    "calc.total.desc": "Bu sizin təxmini aylıq karbon izinizi (CO₂) təmsil edir.",
    "calc.tree.title": "Sıfırlamaq üçün lazım olan ağac",
    "calc.tree.unit": "ədəd (illik)",
    
    // Events
    "events.title": "Gələcəkdən Gələn Tədbirlər",
    "events.desc": "Davamlı inkişaf hədəflərini dəstəkləyən qarşıdan gələn seminarlar, aksiyalar və panellər.",
    "events.view_all": "Bütün tədbirləri gör",
    "events.event1.title": "Yaşıl Kampus Günü: Kütləvi Ağacəkmə",
    "events.event1.month": "Okt",
    "events.event1.loc": "Qeydiyyat Mərkəzi qarşısı",
    "events.event1.cat": "Aksiya",
    "events.event2.title": "Təkrar Emal Seminarı: Gələcək Bizim Əlimizdə",
    "events.event2.month": "Okt",
    "events.event2.loc": "Akt Zalı",
    "events.event2.cat": "Təhsil",
    "events.event3.title": "Alternativ Enerji Mənbələri Sərgisi",
    "events.event3.month": "Noy",
    "events.event3.loc": "Əsas Korpus Foye",
    "events.event3.cat": "Sərgi",
    "events.register": "Qeydiyyatdan Keç",
    
    // Gallery
    "gallery.title": "Mühit və İcma",
    "gallery.desc": "Kampüsdəki davamlılıq təşəbbüslərindən ən parlaq anlar.",

    // FAQ
    "faq.title": "Tez-Tez Verilən Suallar",
    "faq.desc": "SDU-nun davamlı inkişaf fəaliyyətləri haqqında suallarınızın cavabları.",
    "faq.q1": "DİM (Dayanıqlı İnkişaf Məqsədləri) nədir?",
    "faq.a1": "Dayanıqlı İnkişaf Məqsədləri BMT tərəfindən irəli sürülmüş yoxsulluğun aradan qaldırılması, planetin qorunması və hamı üçün sülh və rifahın təmin edilməsini hədəfləyən 17 qlobal məqsəddir. SDU olaraq biz bu məqsədlərə öz siyasət və tədqiqatlarımızla güclü dəstək veririk.",
    "faq.q2": "Tələbələr ekoloji layihələrə necə qoşula bilər?",
    "faq.a2": "Tələbələrimiz il boyu keçirilən 'Yaşıl Kampus' ağacəkmə aksiyalarına, təkrar emal emalatxanalarına və Dayanıqlılıq İnkubatoruna birbaşa portalımızdakı Tədbirlər Təqvimi bölməsindən qeydiyyatdan keçərək qoşula bilərlər.",
    "faq.q3": "Universitetin 2030 hədəfi nədir?",
    "faq.a3": "Əsas hədəfimiz 2030-cu ilə qədər kampus daxilində tam sıfır karbon emissiyasına (Net-Zero) nail olmaq, bərpa olunan enerjiyə keçid etmək və qlobal dayanıqlılıq üzrə reytinqlərdə qabaqcıl ali təhsil müəssisələrindən birinə çevrilməkdir.",
    "faq.q4": "Təkrar emal qutuları kampusda harada yerləşir?",
    "faq.a4": "Əsas tədris binalarının foyelərində, kitabxanada, yeməkxana ərazisində və yataqxanaların girişində xüsusi qeyd edilmiş ağıllı təkrar emal qutuları (kağız, plastik və ümumi tullantı) mövcuddur.",

    // Contact
    "contact.title": "Əlaqə və Ünvan",
    "contact.desc": "Bizimlə əlaqə saxlayaraq davamlı gələcək üçün birgə addımlayaq.",
    "contact.info_center": "Məlumat Mərkəzi",
    "contact.address.label": "Ünvan",
    "contact.address.title": "Məkan & Ofisimiz",
    "contact.address": "Sumqayıt, 43-cü məhəllə, SDU Əsas Bina, Otaq 115",
    "contact.phone.label": "Telefon",
    "contact.email.label": "Elektron Poçt",
    "contact.email": "sustainability@sdu.edu.az",
    "contact.phone": "+994 18 642 09 30",
    "contact.hours.label": "İş Saatları",
    "contact.hours": "B.e. - C. : 09:00 - 18:00",
    "contact.link": "Rəsmi Veb-Sayta Keçid",
    "contact.btn": "Təşəbbüsə qoşul",

    // Footer
    "footer.rights": "Bütün hüquqlar qorunur.",

    // Environmental Strategy Page
    "env.badge": "Strateji İstiqamət 2",
    "env.title": "Ekoloji Strategiya",
    "env.desc": "Karbon izimizi, enerji sərfiyyatımızı və biomüxtəlifliyə təsirimizi GRI standartlarına uyğun illik hesabatlar vasitəsilə ölçür, idarə edir və nəşr edirik.",

    "env.metric1.label": "2020-ci il baza göstəricisinə nisbətən karbon azalması",
    "env.metric2.label": "İstehsal edilən bərpa olunan enerji",
    "env.metric3.label": "İllik su qənaəti",
    "env.metric4.label": "2030-cu ilədək hədəf",

    "env.initiatives.title": "Aktiv Təşəbbüslər",

    "env.init1.title": "Günəş Enerjisinin Genişləndirilməsi",
    "env.init1.status": "Aktiv",
    "env.init1.desc": "2025-ci ilə qədər enerji ehtiyacının 40%-ni ödəmək üçün kampus damlarında 500 kVt günəş panelləri quraşdırılır.",

    "env.init2.title": "Yağış Suyunun Toplanması Sistemi",
    "env.init2.status": "Aktiv",
    "env.init2.desc": "Kampüs miqyaslı toplama infrastrukturu artıq hər il 1,2 milyondan çox litr su bərpa edir.",

    "env.init3.title": "Tullantısız Kampus Proqramı",
    "env.init3.status": "Davam edir",
    "env.init3.desc": "Bütün binalarda tullantı ayrışdırma stansiyaları, kompostlaşdırma və birdəfəlik plastikdən imtina.",

    "env.init4.title": "Şəhər Yaşıl Zolağı",
    "env.init4.status": "Planlaşdırılır",
    "env.init4.desc": "Əsas kampusun ətrafında yerli bitki növləri ilə 3 hektar biomüxtəliflik koridoru.",

    "env.cta.title": "Ekoloji Hesabatlarımıza Daxil Olun",
    "env.cta.desc": "Tam GRI standartlarına uyğun davamlılıq hesabatları SDU Sənəd Portalından yükləmək üçün mövcuddur.",
    "env.cta.btn": "Ana Səhifəyə Qayıt",

    // Social Impact Page
    "soc.badge": "Strateji İstiqamət 3",
    "soc.title": "Sosial Təsir və İnklüzivlik",
    "soc.desc": "İnklüziv proqramlar, əlilliyi olan şəxslərə dəstək, gender bərabərliyi təşəbbüsləri və icma tərəfdaşlıqları vasitəsilə bərabərliyi inkişaf etdiririk.",
    "soc.metric1.label": "Maliyyə yardımı alan tələbələr",
    "soc.metric2.label": "STEM proqramlarında qadınlar",
    "soc.metric3.label": "İcma dəstək layihələri",
    "soc.metric4.label": "Kampusun əlçatanlıq reytinqi",
    "soc.initiatives.title": "Aktiv Təşəbbüslər",
    "soc.init1.title": "STEM-də Qadınlar Mentoru Proqramı",
    "soc.init1.desc": "Texniki sahələrdə təmsilçiliyi artırmaq üçün qadın tələbələri sənaye liderləri ilə birləşdirir.",
    "soc.init1.status": "Aktiv",
    "soc.init2.title": "Əlçatan Kampus Təşəbbüsü",
    "soc.init2.desc": "Bütün kampus obyektlərini panduslar, liftlər və brayl lövhələri ilə təkmilləşdirmək.",
    "soc.init2.status": "Davam edir",
    "soc.init3.title": "Kənd Tələbələrinə Dəstək Fondu",
    "soc.init3.desc": "Ucqar bölgələrdən gələn tələbələr üçün mənzil və təqaüd təminatı.",
    "soc.init3.status": "Aktiv",
    "soc.init4.title": "İcma Könüllülük Proqramı",
    "soc.init4.desc": "Yerli QHT-lər və məktəblər üçün tələbə könüllü saatlarının əlaqələndirilməsi.",
    "soc.init4.status": "Planlaşdırılır",
    "soc.cta.title": "İcma Səylərimizə Qoşulun",
    "soc.cta.desc": "Sosial təşəbbüslərimizdə iştirak edin və bu gün fərq yaradın.",
    "soc.cta.btn": "İmkanları Kəşf Edin",

    // SDG Research Page
    "res.badge": "Strateji İstiqamət 4",
    "res.title": "DİM Tədqiqat Nəticələri",
    "res.desc": "BMT-nin 17 Qlobal Məqsədinə birbaşa töhfə verən elmi məqalələr, siyasət xülasələri və innovasiya layihələri istehsal edirik.",
    "res.metric1.label": "Dərc edilmiş elmi məqalələr",
    "res.metric2.label": "Aktiv tədqiqat qrantları",
    "res.metric3.label": "Beynəlxalq tərəfdaşlıqlar",
    "res.metric4.label": "Tələbə tədqiqat layihələri",
    "res.initiatives.title": "Əsas Tədqiqat Layihələri",
    "res.init1.title": "Bərpa Olunan Enerji Laboratoriyası",
    "res.init1.desc": "Şəhər mühitləri üçün sərfəli günəş enerjisi saxlama həllərinin inkişafı.",
    "res.init1.status": "Aktiv",
    "res.init2.title": "Xəzər Dənizi Biomüxtəliflik Tədqiqatı",
    "res.init2.desc": "Qlobal QHT-lərlə tərəfdaşlıqda dəniz həyatı dəyişikliklərinin və çirklənmə səviyyələrinin izlənməsi.",
    "res.init2.status": "Davam edir",
    "res.init3.title": "Dayanıqlı Kənd Təsərrüfatı Texnologiyaları",
    "res.init3.desc": "Regional əkinçilikdə suyun optimallaşdırılması üçün IoT sensorlarının sınaqdan keçirilməsi.",
    "res.init3.status": "Planlaşdırılır",
    "res.init4.title": "Yaşıl İqtisadiyyat Siyasət Sənədləri",
    "res.init4.desc": "Sirkulyar iqtisadiyyata keçid üzrə yerli hökumətə məsləhətlər.",
    "res.init4.status": "Aktiv",
    "res.cta.title": "Tədqiqat Portalımıza Daxil Olun",
    "res.cta.desc": "Ən son nəşrlərimizi oxuyun və əməkdaşlıq imkanlarını kəşf edin.",
    "res.cta.btn": "Nəşrlərə Baxın",

    // Education & Curriculum Page
    "edu.badge": "Strateji İstiqamət 5",
    "edu.title": "Təhsil və Kurikulum",
    "edu.desc": "Bütün dərəcə proqramlarına davamlılıq kompetensiyalarını daxil edərək, hər bir SDU məzununu yaşıl keçidə rəhbərlik etmək üçün biliklərlə təmin edirik.",
    "edu.metric1.label": "DİM-ləri inteqrasiya edən kurslar",
    "edu.metric2.label": "Davamlı inkişaf dərəcələri",
    "edu.metric3.label": "Yaşıl təhsil üzrə təlim keçmiş müəllimlər",
    "edu.metric4.label": "Yaşıl kurslarda oxuyan tələbələr",
    "edu.initiatives.title": "Kurikulum Yeniləmələri",
    "edu.init1.title": "Məcburi 'Yaşıl Keçid' Əsas Kursu",
    "edu.init1.desc": "Bütün fakültələrdə bütün birinci kurs tələbələri üçün tələb olunan təməl kurs.",
    "edu.init1.status": "Aktiv",
    "edu.init2.title": "Davamlı İnkişaf üzrə Magistratura",
    "edu.init2.desc": "Gələn tədris ilində yeni fənlərarası magistr dərəcəsinin tətbiqi.",
    "edu.init2.status": "Davam edir",
    "edu.init3.title": "Müəllimlər üçün Yaşıl Təlim Seminarları",
    "edu.init3.desc": "Professorların DİM-ləri mövcud tədris planlarına inteqrasiya etmələri üçün alətlərlə təchiz edilməsi.",
    "edu.init3.status": "Aktiv",
    "edu.init4.title": "Tələbə Davamlılıq İnkubatoru",
    "edu.init4.desc": "Tələbələrin ekoloji təmiz biznes modelləri hazırlaması üçün laboratoriya.",
    "edu.init4.status": "Planlaşdırılır",
    "edu.cta.title": "Akademik Təkliflərimizi Nəzərdən Keçirin",
    "edu.cta.desc": "SDU-da tədris planları, yaşıl dərəcələr və təlim proqramlarını kəşf edin.",
    "edu.cta.btn": "Kurs Kataloquna Baxın",

    // Governance & Policy Page
    "gov.title": "İdarəetmə və Siyasət",
    "gov.desc": "Uzunmüddətli təsir göstərən şəffaf institusional çərçivələrin, etik qərar qəbuletmə proseslərinin və sübutlara əsaslanan siyasətlərin qurulması.",
    "gov.pillars.title": "İdarəetmə Sütunlarımız",
    "gov.pillars.desc": "SDU-nun davamlılıq gündəmini necə idarə etdiyini təməlləndirən dörd bir-biri ilə əlaqəli prinsip.",
    "gov.pillar1.title": "İnstitusional Dürüstlük",
    "gov.pillar1.desc": "Universitet rəhbərliyinin hər səviyyəsində davamlılıq məsuliyyətini təmin edən möhkəm idarəetmə çərçivələrinin qurulması.",
    "gov.pillar2.title": "Sübutlara Əsaslanan Siyasət",
    "gov.pillar2.desc": "Elmi rəylə təsdiqlənmiş məlumatlar, beynəlxalq standartlar və maraqlı tərəflərlə məsləhətləşmə əsasında davamlılıq siyasətlərinin hazırlanması və nəzərdən keçirilməsi.",
    "gov.pillar3.title": "Şəffaf Hesabatlılıq",
    "gov.pillar3.desc": "GRI və IESBA standartlarına uyğun illik davamlılıq hesabatlarının nəşr edilməsi və tam ictimai məsuliyyət.",
    "gov.pillar4.title": "Maraqlı Tərəflərin İştirakı",
    "gov.pillar4.desc": "Davamlılıq təşəbbüslərini birgə hazırlamaq üçün müəllimlər, tələbələr, hökumət nümayəndələri və QHT-lər arasında mənalı dialoqun yaradılması.",
    "gov.docs.title": "Siyasət Sənədləri",
    "gov.doc1.title": "SDU Davamlılıq Strategiyası 2024–2030",
    "gov.doc1.tag": "Strategiya",
    "gov.doc2.title": "İllik GRI Davamlılıq Hesabatı",
    "gov.doc2.tag": "Hesabat",
    "gov.doc3.title": "Kampus Karbon Neytrallığı Yol Xəritəsi",
    "gov.doc3.tag": "Yol Xəritəsi",
    "gov.doc4.title": "Maraqlı Tərəflərin İştirakı Nizamnaməsi",
    "gov.doc4.tag": "Siyasət",
    "gov.cta.title": "Siyasət İşimizə Töhfə Verin",
    "gov.cta.desc": "Müəllimlər, tələbələr və icma tərəfdaşları SDU Davamlılıq Portalı vasitəsilə siyasət təklifləri göndərə bilərlər.",
    "gov.cta.btn": "Ana Səhifəyə Qayıt",

    // Governance & Accountability (Page 2) - AZ
    "gov2.intro": "Sumqayıt Dövlət Universiteti davamlı inkişafı dəstəkləyən məsul idarəetmə və şəffaf institusional praktikalarla bağlıdır. Universitet etik davranış, bərabərlik və inklüzivlik, ekoloji məsuliyyət və məsul maliyyə idarəçiliyinə rəhbərlik edən siyasətlər və idarəetmə mexanizmləri yaradıb.",
    "gov2.section1.title": "İnstitusional İdarəetmə və Dayanıqlılıq Çərçivəsi",
    "gov2.section1.desc": "İdarəetmə strukturumuz hər səviyyədə məsuliyyəti təmin edir, dayanıqlılıq nəticələri üçün aydın məsuliyyət xəttləri yaradır.",
    "gov2.section2.title": "Əsas Siyasətlər",
    "gov2.policy1.title": "Akademik Azadlıq Siyasəti",
    "gov2.policy1.desc": "Universitetdə akademik azadlığın, açıq tədqiqatın və intellektual müxtəlifliyin qorunmasını təmin edən siyasət.",
    "gov2.policy2.title": "Antikorrupsiya Siyasəti",
    "gov2.policy2.desc": "Korrupsiyanın qarşısının alınması, şəffaflığın təşviqi və bütün universitet əməliyyatlarında etik davranışın təmin edilməsi çərçivəsi.",
    "gov2.policy3.title": "Ayrı-seçkiliyə Qarşı Siyasət",
    "gov2.policy3.desc": "Hər növ ayrı-seçkiliyi qadağan edən və inklüziv, hörmətli akademik mühit yaradan siyasət.",
    "gov2.policy4.title": "Təqibə Qarşı Siyasət",
    "gov2.policy4.desc": "Təqibin qarşısını almaq və bütün üzvlər üçün təhlükəsiz təhsil və iş mühiti təmin etmək üçün hərtərəfli təlimatlar.",
    "gov2.policy5.title": "İqlim Fəaliyyəti və Davamlılıq Siyasəti",
    "gov2.policy5.desc": "Karbon azaltma, yaşıl təşəbbüslər və davamlı kampus əməliyyatları vasitəsilə iqlim dəyişikliyinə yönəlmiş strateji siyasət.",
    "gov2.policy6.title": "Bərabərlik, Müxtəliflik və İnklüzivlik Siyasəti",
    "gov2.policy6.desc": "Bərabər imkanları təşviq edən, müxtəlifliyi qiymətləndirən və inklüziv universitet mədəniyyəti quran siyasət.",
    "gov2.policy7.title": "Bərabərlik, Müxtəliflik və İnklüzivlik Çərçivəsi",
    "gov2.policy7.desc": "Bərabərlik, müxtəliflik və inklüzivliyin inkişafı üçün strategiyaları və fəaliyyət planlarını əhatə edən strukturlaşdırılmış çərçivə.",
    "gov2.policy8.title": "İnklüziv Təhsil və Əlçatanlıq Çərçivəsi",
    "gov2.policy8.desc": "Əlilliyi olan və xüsusi ehtiyacları olan tələbələr daxil olmaqla, bütün tələbələr üçün əlçatan təhsili təmin edən çərçivə.",
    "gov2.policy9.title": "Etik Təşkilati Dəyərlər Siyasəti",
    "gov2.policy9.desc": "Təşkilati idarəetmə və qərar qəbulu üçün etik standartlar və əsas dəyərlər müəyyən edən təlimatlar.",
    "gov2.policy10.title": "Etik Dəyərlər Siyasəti",
    "gov2.policy10.desc": "Akademik və peşəkar mühitdə tələbə və işçi davranışına rəhbərlik edən etik prinsipləri müəyyən edən siyasət.",
    "gov2.policy11.title": "İnsan Alveri Qarşısının Alınması Siyasəti",
    "gov2.policy11.desc": "Universitet icmasında insan alverinin qarşısının alınması və həssas şəxslərin qorunması üçün tədbirləri əhatə edən siyasət.",
    "gov2.policy12.title": "Tələbə Təhlükəsizliyi Siyasəti",
    "gov2.policy12.desc": "Bütün kampus fəaliyyətlərində tələbələrin fiziki və psixoloji təhlükəsizliyini təmin edən hərtərəfli siyasət.",
    "gov2.policy13.title": "İanələr və Maliyyələşdirmə üzrə Davamlılıq Siyasəti",
    "gov2.policy13.desc": "İanə və maliyyə mənbələrinin universitetin davamlılıq və etik standartlarına uyğunluğunu təmin edən təlimatlar.",
    "gov2.policy14.title": "Davamlı İnvestisiya Siyasəti",
    "gov2.policy14.desc": "İnvestisiya qərarlarını ekoloji və sosial cəhətdən məsuliyyətli imkanlara yönəldən siyasət.",
    "gov2.policy15.title": "Davamlı Satınalma Siyasəti",
    "gov2.policy15.desc": "Ekoloji, sosial və iqtisadi davamlılıq meyarlarına cavab verən mal və xidmətlərin tədarükü çərçivəsi.",
    "gov2.section3.title": "Dayanıqlılıq Rəhbərliyi və Komitələri",
    "gov2.section3.desc": "Dayanıqlılıq gündəmimizi irəli aparan həsr olunmuş komandalar.",
    "gov2.committee1.title": "Dayanıqlılıq üzrə Rəhbər Komitə",
    "gov2.committee1.desc": "Strateji dayanıqlılıq təşəbbüslərinə nəzarət edən icra rəhbərliyi.",
    "gov2.committee2.title": "İşçi Qrupları",
    "gov2.committee2.desc": "Xüsusi dayanıqlılıq layihələrini həyata keçirən funksional komandalar.",
    "gov2.committee3.title": "Rəhbərlik Komandası",
    "gov2.committee3.desc": "Dayanıqlılıq nəticələrinə görə məsul olan baş idarəetmə.",
    "gov2.section4.title": "İnstitusional Öhdəliklər",
    "gov2.commitment1.title": "BMT DİM Öhdəliyi",
    "gov2.commitment1.desc": "17 Dayanıqlı İnkişaf Məqsədinin hamısı ilə uyğunlaşma.",
    "gov2.commitment2.title": "Karbon Neytrallığı Məqsədi",
    "gov2.commitment2.desc": "2030-cu ilə qədər xalis sıfır emissiya hədəfi.",
    "gov2.commitment3.title": "Şəffaflıq Öhdəliyi",
    "gov2.commitment3.desc": "Dayanıqlılıq performansı haqqında illik ictimai hesabat.",
    "gov2.commitment4.title": "İcma Tərəfdaşlığı",
    "gov2.commitment4.desc": "Yerli maraqlı tərəflərlə əməkdaşlıq yanaşması.",
    "gov2.cta": "İdarəetmə Haqqında Daha Ətraflı",

    // Strategy & Reporting - AZ
    "strat.intro": "Sumqayıt Dövlət Universiteti davamlılıq prinsiplərini tədricən institusional strategiya və planlaşdırma proseslərinə inteqrasiya edir. Universitet fəaliyyətini BMT-nin Dayanıqlı İnkişaf Məqsədləri (DİM) ilə uyğunlaşdırır və daxili hesabat və qiymətləndirmə mexanizmləri vasitəsilə irəliləyişi izləyir.",
    "strat.section1.title": "İqlim Fəalliyəti və Dayanıqlılıq Strategiyası",
    "strat.strategy1.title": "Karbon Azaltma Strategiyası",
    "strat.strategy1.desc": "2027-ci ilə qədər karbon emissiyasını 50% azaltmaq üçün hərtərəfli plan.",
    "strat.strategy2.title": "Enerji Keçidi Planı",
    "strat.strategy2.desc": "2028-ci ilə qədər 100% bərpa olunan enerji mənbələrinə keçid.",
    "strat.strategy3.title": "Biomüxtəlifliyin Qorunması",
    "strat.strategy3.desc": "Kampus ekosistemlərinin və yerli növlərin qorunması və inkişafı.",
    "strat.section2.title": "DİM Uyğunluğu",
    "strat.sdg.desc": "Fəaliyyətimiz BMT-nin 17 Dayanıqlı İnkişaf Məqsədinin hamısı ilə uyğundur.",
    "strat.section3.title": "Dayanıqlılıq Məqsədləri və Prioritetləri",
    "strat.goal1.title": "2030-cu ilə qədər Net-Zero",
    "strat.goal1.desc": "Bütün kampus əməliyyatlarında karbon neytrallığına nail olmaq.",
    "strat.goal2.title": "Tullantısız Kampus",
    "strat.goal2.desc": "Azaltma və təkrar emal vasitəsilə tullantıların 90%-ni poliqonlardan yayındırmaq.",
    "strat.goal3.title": "100% Bərpa Olunan Enerji",
    "strat.goal3.desc": "Bütün obyektləri təmiz, bərpa olunan mənbələrlə təchiz etmək.",
    "strat.goal4.title": "Su Qənaəti",
    "strat.goal4.desc": "Səmərəlilik tədbirləri vasitəsilə su istehlakını 40% azaltmaq.",
    "strat.goal5.title": "Hamı üçün Yaşıl Təhsil",
    "strat.goal5.desc": "Davamlılığı hər dərəcə proqramına inteqrasiya etmək.",
    "strat.section4.title": "DİM Hesabatları və İrəliləyiş",
    "strat.report1.title": "İllik Dayanıqlılıq Hesabatı 2024",
    "strat.report2.title": "DİM İrəliləyiş Hesabatı 2023",
    "strat.report3.title": "İqlim Fəalliyəti Yenilənməsi 2024",
    "strat.report4.title": "GRI Uyğunluq Hesabatı",
    "strat.download": "PDF Yüklə",
    "strat.section5.title": "Əsas Göstəricilər",
    "strat.indicator1": "Karbon Emissiyası",
    "strat.indicator2": "Bərpa Olunan Enerji",
    "strat.indicator3": "Təkrar Emal",
    "strat.indicator4": "Su Qənaəti",
    "strat.indicator5": "Yaşıl Kurslar",
    "strat.indicator6": "İcma Layihələri",
    "strat.cta": "Tam Hesabatları Yüklə",

    // Research for Sustainable Development (Page 2) - AZ
    "res2.intro": "Sumqayıtın tarixi sənaye inkişafı davamlılıq tədqiqatları üçün unikal kontekst yaradır. Bu gün şəhərin davam edən ekoloji təkmilləşdirmə və bərpa səyləri ekoloji bərpa, çirklənmənin azaldılması və davamlı resurs idarəçiliyi üzrə tədqiqatlar üçün imkanlar təqdim edir.",
    "res2.section1.title": "Sumqayıt: Tədqiqat Konteksti",
    "res2.section2.title": "DİM-lə Əlaqəli Tədqiqat Layihələri",
    "res2.project1.title": "Bərpa Olunan Enerji Saxlanması",
    "res2.project1.desc": "Şəhər mühitləri üçün sərfəli günəş enerjisi saxlama həllərinin inkişafı.",
    "res2.project2.title": "Xəzər Dənizi Biomüxtəlifliyi",
    "res2.project2.desc": "Qlobal QHT-lərlə tərəfdaşlıqda dəniz həyatı dəyişikliklərinin və çirklənmə səviyyələrinin izlənməsi.",
    "res2.project3.title": "Dayanıqlı Kənd Təsərrüfatı",
    "res2.project3.desc": "Regional əkinçilikdə suyun optimallaşdırılması üçün IoT sensorlarının sınaqdan keçirilməsi.",
    "res2.project4.title": "Hava Keyfiyyətinin Monitorinqi",
    "res2.project4.desc": "Sənaye və yaşayış zonalarında hava keyfiyyətinin real vaxt izlənməsi.",
    "res2.project5.title": "Yaşıl İqtisadiyyat Siyasəti",
    "res2.project5.desc": "Sirkulyar iqtisadiyyata keçid üzrə yerli hökumətə məsləhətlər.",
    "res2.project6.title": "Tullantı İdarəetmə Texnologiyası",
    "res2.project6.desc": "Tullantıların azaldılması və təkrar emalı üçün innovativ həllər.",
    "res2.section3.title": "Tədqiqat Tərəfdaşlıqları",
    "res2.partner1.title": "Beynəlxalq Universitetlər",
    "res2.partner2.title": "Tədqiqat İnstitutları",
    "res2.partner3.title": "QHT-lər və Fondlar",
    "res2.partner4.title": "Hökumət Agentlikləri",
    "res2.partner5.title": "Sənaye Tərəfdaşları",
    "res2.section4.title": "Tədqiqat Mərkəzləri və Laboratoriyalar",
    "res2.center1.title": "Bərpa Olunan Enerji Laboratoriyası",
    "res2.center1.desc": "Günəş, külək və enerji saxlama texnologiyaları üzrə qabaqcıl tədqiqatlar.",
    "res2.center2.title": "Ətraf Mühit Tədqiqatları Mərkəzi",
    "res2.center2.desc": "Yerli ekosistem sağlamlığının və biomüxtəlifliyin monitorinqi və təhlili.",
    "res2.center3.title": "Dayanıqlılıq İnnovasiya Mərkəzi",
    "res2.center3.desc": "Yaşıl texnologiyaların və davamlı biznes modellərinin inkubasiyası.",
    "res2.center4.title": "Data Analitikası Laboratoriyası",
    "res2.center4.desc": "Dayanıqlılıq metrikaları və hesabatı üçün böyük data həlləri.",
    "res2.section5.title": "Tələbə Tədqiqat Layihələri",
    "res2.student1.title": "Bakalavr Layihələri",
    "res2.student2.title": "Magistr Dissertasiyaları",
    "res2.student3.title": "Fəlsəfə Doktoru Dissertasiyaları",
    "res2.student4.title": "İnnovasiya Çempionatı Qalibləri",
    "res2.student5.title": "Qrant Alıcıları",
    "res2.cta": "Tədqiqat İmkanlarını Kəşf Edin",

    // Sustainable Education (Page 2) - AZ
    "edu2.intro": "Sumqayıt Dövlət Universiteti davamlılıq şüuru və məsul vətəndaşlığı təşviq edən təhsili dəstəkləyir. Davamlılıqla əlaqəli mövzular tədricən tədrisə, tələbə fəaliyyətlərinə və akademik təşəbbüslərə inteqrasiya olunur.",
    "edu2.section1.title": "Kurikulumda Davamlılıq Mövzuları",
    "edu2.topic1.title": "İqlim Dəyişikliyi Elmi",
    "edu2.topic1.desc": "İqlim dəyişikliyinin elmi əsasları və təsirlərinin başa düşülməsi.",
    "edu2.topic2.title": "Sirkulyar İqtisadiyyat",
    "edu2.topic2.desc": "Tullantıların azaldılması və resurs səmərəliliyi prinsipləri.",
    "edu2.topic3.title": "Sosial Məsuliyyət",
    "edu2.topic3.desc": "Etik biznes praktikaları və icma ilə əlaqə.",
    "edu2.topic4.title": "Ətraf Mühit Etikası",
    "edu2.topic4.desc": "Ətraf mühitin qorunmasının fəlsəfi əsasları.",
    "edu2.topic5.title": "Yaşıl Texnologiya",
    "edu2.topic5.desc": "Təmiz enerji və davamlı materiallarda innovasiyalar.",
    "edu2.topic6.title": "Dayanıqlı İnkişaf Məqsədləri",
    "edu2.topic6.desc": "Davamlılıq problemlərini həll etmək üçün qlobal çərçivə.",
    "edu2.section2.title": "Müvafiq Kurslar və Proqramlar",
    "edu2.course1.title": "Davamlılığa Giriş",
    "edu2.course1.desc": "Davamlı inkişafın əsas konsepsiya və prinsipləri.",
    "edu2.course2.title": "Ətraf Mühit İdarəçiliyi",
    "edu2.course2.desc": "Ətraf mühit resurslarının idarə edilməsinə sistemli yanaşma.",
    "edu2.course3.title": "Yaşıl Biznes Praktikaları",
    "edu2.course3.desc": "Müasir təşkilatlar üçün davamlı strategiyalar.",
    "edu2.course4.title": "Bərpa Olunan Enerji Sistemləri",
    "edu2.course4.desc": "Təmiz enerji həllərinin layihələndirilməsi və tətbiqi.",
    "edu2.course5.title": "Davamlı Şəhər Planlaşdırması",
    "edu2.course5.desc": "Yaşana bilən, səmərəli və yaşıl şəhərlərin yaradılması.",
    "edu2.course6.title": "Davamlı İnkişaf üzrə Magistratura",
    "edu2.course6.desc": "Qabaqcıl fənlərarası magistr proqramı.",
    "edu2.section3.title": "Tələbə Davamlılıq Təşəbbüsləri",
    "edu2.init1.title": "Akademik Azadlıq Siyasəti",
    "edu2.init1.desc": "Universitetdə akademik azadlığın, açıq tədqiqatın və intellektual müxtəlifliyin qorunmasını təmin edən siyasət.",
    "edu2.init2.title": "Antikorrupsiya Siyasəti",
    "edu2.init2.desc": "Korrupsiyanın qarşısının alınması, şəffaflığın təşviqi və bütün universitet əməliyyatlarında etik davranışın təmin edilməsi çərçivəsi.",
    "edu2.init3.title": "Ayrı-seçkiliyə Qarşı Siyasət",
    "edu2.init3.desc": "Hər növ ayrı-seçkiliyi qadağan edən və inklüziv, hörmətli akademik mühit yaradan siyasət.",
    "edu2.init4.title": "Təqibə Qarşı Siyasət",
    "edu2.init4.desc": "Təqibin qarşısını almaq və bütün üzvlər üçün təhlükəsiz təhsil və iş mühiti təmin etmək üçün hərtərəfli təlimatlar.",
    "edu2.init5.title": "İqlim Fəaliyyəti və Davamlılıq Siyasəti",
    "edu2.init5.desc": "Karbon azaltma, yaşıl təşəbbüslər və davamlı kampus əməliyyatları vasitəsilə iqlim dəyişikliyinə yönəlmiş strateji siyasət.",
    "edu2.init6.title": "Bərabərlik, Müxtəliflik və İnklüzivlik Siyasəti",
    "edu2.init6.desc": "Bərabər imkanları təşviq edən, müxtəlifliyi qiymətləndirən və inklüziv universitet mədəniyyəti quran siyasət.",
    "edu2.init7.title": "Bərabərlik, Müxtəliflik və İnklüzivlik Çərçivəsi",
    "edu2.init7.desc": "Bərabərlik, müxtəliflik və inklüzivliyin inkişafı üçün strategiyaları və fəaliyyət planlarını əhatə edən strukturlaşdırılmış çərçivə.",
    "edu2.init8.title": "İnklüziv Təhsil və Əlçatanlıq Çərçivəsi",
    "edu2.init8.desc": "Əlilliyi olan və xüsusi ehtiyacları olan tələbələr daxil olmaqla, bütün tələbələr üçün əlçatan təhsili təmin edən çərçivə.",
    "edu2.init9.title": "Etik Təşkilati Dəyərlər Siyasəti",
    "edu2.init9.desc": "Təşkilati idarəetmə və qərar qəbulu üçün etik standartlar və əsas dəyərlər müəyyən edən təlimatlar.",
    "edu2.init10.title": "Etik Dəyərlər Siyasəti",
    "edu2.init10.desc": "Akademik və peşəkar mühitdə tələbə və işçi davranışına rəhbərlik edən etik prinsipləri müəyyən edən siyasət.",
    "edu2.init11.title": "İnsan Alveri Qarşısının Alınması Siyasəti",
    "edu2.init11.desc": "Universitet icmasında insan alverinin qarşısının alınması və həssas şəxslərin qorunması üçün tədbirləri əhatə edən siyasət.",
    "edu2.init12.title": "Tələbə Təhlükəsizliyi Siyasəti",
    "edu2.init12.desc": "Bütün kampus fəaliyyətlərində tələbələrin fiziki və psixoloji təhlükəsizliyini təmin edən hərtərəfli siyasət.",
    "edu2.init13.title": "İanələr və Maliyyələşdirmə üzrə Davamlılıq Siyasəti",
    "edu2.init13.desc": "İanə və maliyyə mənbələrinin universitetin davamlılıq və etik standartlarına uyğunluğunu təmin edən təlimatlar.",
    "edu2.init14.title": "Davamlı İnvestisiya Siyasəti",
    "edu2.init14.desc": "İnvestisiya qərarlarını ekoloji və sosial cəhətdən məsuliyyətli imkanlara yönəldən siyasət.",
    "edu2.init15.title": "Davamlı Satınalma Siyasəti",
    "edu2.init15.desc": "Ekoloji, sosial və iqtisadi davamlılıq meyarlarına cavab verən mal və xidmətlərin tədarükü çərçivəsi.",
    "edu2.section4.title": "Eko-Klub Fəaliyyətləri",
    "edu2.eco1.title": "Ağacəkmə Tədbirləri",
    "edu2.eco2.title": "Çimərlik Təmizliyi",
    "edu2.eco3.title": "Davamlılıq Seminarları",
    "edu2.eco4.title": "Sənədli Film Göstəriləri",
    "edu2.section5.title": "Seminar və Treyninqlər",
    "edu2.workshop1.title": "Qonaq Mühazirələri",
    "edu2.workshop2.title": "Ekspert Panelləri",
    "edu2.workshop3.title": "Praktik Treyninqlər",
    "edu2.workshop4.title": "Karyera Sərgiləri",
    "edu2.workshop5.title": "Tədqiqat Simpoziumları",
    "edu2.cta": "Kurs Kataloquna Bax",

    // Community & Social Impact - AZ
    "comm.intro": "Universitet cəmiyyətin inkişafına töhfə verməyin əhəmiyyətini qəbul edir. Tərəfdaşlıqlar, maarifləndirmə fəaliyyətləri və ictimai iştirak təşəbbüsləri vasitəsilə Sumqayıt Dövlət Universiteti sosial inklüzivliyi, ekoloji şüuru və icma inkişafını təşviq edir.",
    "comm.section1.title": "İcma ilə Əlaqə Layihələri",
    "comm.outreach1.title": "Kənd Təhsilinə Dəstək",
    "comm.outreach1.desc": "Az təmin edilmiş kənd ərazilərinə təhsil resurslarının təqdim edilməsi.",
    "comm.outreach2.title": "Səhiyyə Maarifləndirməsi",
    "comm.outreach2.desc": "İctimai sağlamlıq təhsili və skrininq proqramları.",
    "comm.outreach3.title": "Rəqəmsal Savadlılıq Proqramı",
    "comm.outreach3.desc": "Bütün yaşlardan olan icma üzvlərinə rəqəmsal bacarıqların öyrədilməsi.",
    "comm.outreach4.title": "Gənclərin Gücləndirilməsi",
    "comm.outreach4.desc": "Gənclər üçün liderlik inkişafı və mentorluq.",
    "comm.outreach5.title": "Yaşlılara Qayğı Təşəbbüsü",
    "comm.outreach5.desc": "Yaşlı vətəndaşlar üçün dəstək xidmətləri və yoldaşlıq.",
    "comm.outreach6.title": "Əlilliyə Dəstək",
    "comm.outreach6.desc": "Əlçatanlıq təkmilləşdirmələri və yardım proqramları.",
    "comm.section2.title": "Tərəfdaşlıqlar",
    "comm.partner1.title": "Yerli Hökumət",
    "comm.partner2.title": "Beynəlxalq QHT-lər",
    "comm.partner3.title": "İcma Təşkilatları",
    "comm.partner4.title": "Özəl Sektor",
    "comm.partner5.title": "KİV Tərəfdaşları",
    "comm.partner6.title": "Akademik Müəssisələr",
    "comm.section3.title": "Könüllülük Təşəbbüsləri",
    "comm.volunteer1.title": "Tələbə Könüllülük Korpusu",
    "comm.volunteer1.desc": "Müxtəlif səbəblər üzrə təşkil edilmiş tələbə könüllülüyü.",
    "comm.volunteer2.title": "Müəllimlərin Pro Bono Proqramı",
    "comm.volunteer2.desc": "Müəllimlər tərəfindən ianə edilən peşəkar xidmətlər.",
    "comm.volunteer3.title": "Məzun Mentorluğu",
    "comm.volunteer3.desc": "Məzunların cari tələbələrə və icma gənclərinə mentorluq etməsi.",
    "comm.volunteer4.title": "İcma Xidməti Günləri",
    "comm.volunteer4.desc": "Universitet üzrə əlaqələndirilmiş xidmət günləri.",
    "comm.volunteer5.title": "Fövqəladə Cavab Komandası",
    "comm.volunteer5.desc": "İcma fövqəladə halları üçün sürətli cavab könüllüləri.",
    "comm.section4.title": "Davamlılıq Maarifləndirmə Kampaniyaları",
    "comm.campaign1.title": "İqlim Fəalliyəti Həftəsi",
    "comm.campaign2.title": "Sıfır Tullantı Çəlliyi",
    "comm.campaign3.title": "Biomüxtəliflik Ayı",
    "comm.campaign4.title": "Yaşıl Nəqliyyat Günü",
    "comm.section5.title": "Tələbə İştirakı Fəaliyyətləri",
    "comm.activity1.title": "Davamlılıq Hakatonu",
    "comm.activity2.title": "İcma Bağı Layihəsi",
    "comm.activity3.title": "Sosial İnnovasiya Laboratoriyası",
    "comm.activity4.title": "Mədəni Mübadilə Tədbirləri",
    "comm.activity5.title": "Liderlik Treyninqi",
    "comm.cta": "İcmamıza Qoşulun",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>("en");

  // On mount, load language from localStorage
  useEffect(() => {
    const storedLang = localStorage.getItem("sdu-lang") as Language;
    if (storedLang && (storedLang === "en" || storedLang === "az")) {
      setLanguageState(storedLang);
    } else {
      setLanguageState("az"); // Default to AZ
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("sdu-lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};